version: 2
jobs:
  test:
    docker:
      - image: jiayuyi/chicken:circleci
    steps:
      - checkout
      - run: ./dependencies.sh
      - run: csi *-test.scm
workflows:
  version: 2
  test:
    jobs:
      - test
